normalization:
  "Фитнес Империя (Гоголевский)": "Коммунальная, 20"
  "Гоголевский": "Коммунальная, 20"
  "Коммунальная, 20": "Коммунальная, 20"
  "Коммунальная 20": "Коммунальная, 20"
  "Коммунальная,20": "Коммунальная, 20"
  "Фитнес Империя (Столица)": "Лососинское шоссе, 26"
  "Столица": "Лососинское шоссе, 26"
  "Лососинское шоссе, 26": "Лососинское шоссе, 26"
  "Лососинское шоссе 26": "Лососинское шоссе, 26"
  "Лососинское 26": "Лососинское шоссе, 26"
  "Фитнес Империя (Карельский)": "Карельский (закрыт)"
  "Карельский": "Карельский (закрыт)"
  "Карельский (закрыт)": "Карельский (закрыт)"
  "Клуб не определен (fallback)": "Клуб не определен (fallback)"
  "Фитнес Империя (Промышленная)": "Промышленная, 10"
  "Промышленная, 10": "Промышленная, 10"
  "Промышленная,10": "Промышленная, 10"
  "Промышленная 10": "Промышленная, 10"
  "Промышленная": "Промышленная, 10"
  "Фитнес Империя (Ровио,3)": "Ровио, 3"
  "Ровио, 3": "Ровио, 3"
  "Ровио,3": "Ровио, 3"
  "Ровио 3": "Ровио, 3"
  "Ровио": "Ровио, 3"
