clubs:
  "Коммунальная, 20":
    - "Пеуна Анастасия Ивановна"
    - "Васильева Яна Денисовна"
    - "Абраамян Татьяна Викторовна"
    - "Пилия Анастасия Артуровна"

  "Лососинское шоссе, 26":
    - "Седунова Анна Сергеевна"
    - "Фёдорова Надежда Сергеевна"
    - "Мартынова Дарья Дмитриевна"

  "Карельский (закрыт)":
    - "УТОЧНИТЬ: Карельский"

  "Клуб не определен (fallback)":
    - "УТОЧНИТЬ: клуб не определен"

  "Промышленная, 10":
    - "Васьковская Виктория Петровна"
    - "Лисовская Екатерина Александровна"
    - "Яковлева Александра Владимировна"

  "Ровио, 3":
    - "Соколова Анастасия Александровна"
    - "Анухина Кристина Алексеевна"
    - "Петрова Полина Владимировна"
    - "Фёдорова Милана Андреевна"
