branches:
  "Коммунальная, 20": "Фитнес Империя (Гоголевский)"
  "Лососинское шоссе, 26": "Фитнес Империя (Столица)"
  "Промышленная, 10": "Фитнес Империя (Промышленная)"
  "Ровио, 3": "Фитнес Империя (Ровио)"
  "Карельский (закрыт)": "Фитнес Империя (Ровио)"
