SELECT
    client_ref,
    client_id,
    original_client_ref,
    original_client_id,
    REPLACE(REPLACE(REPLACE(original_client_fio, CHAR(9), N' '), CHAR(10), N' '), CHAR(13), N' ') AS original_client_fio,
    effective_client_ref,
    effective_client_id,
    REPLACE(REPLACE(REPLACE(effective_client_fio, CHAR(9), N' '), CHAR(10), N' '), CHAR(13), N' ') AS effective_client_fio,
    owner_change_ref,
    owner_change_number,
    CONVERT(varchar(19), owner_change_datetime, 120) AS owner_change_datetime,
    owner_change_old_client_ref,
    owner_change_new_client_ref,
    REPLACE(REPLACE(REPLACE(owner_change_modifier_name, CHAR(9), N' '), CHAR(10), N' '), CHAR(13), N' ') AS owner_change_modifier_name,
    owner_change_count_for_membership,
    subscription_ref,
    document_number,
    holder_client_ref,
    payer_client_ref,
    client_role_source,
    product_ref,
    product_code,
    REPLACE(REPLACE(REPLACE(subscription_name, CHAR(9), N' '), CHAR(10), N' '), CHAR(13), N' ') AS subscription_name,
    product_class,
    is_full_subscription,
    is_trial_or_guest,
    is_subrent,
    is_limited_subrent,
    CONVERT(varchar(10), sale_date, 120) AS sale_date,
    CONVERT(varchar(19), sale_datetime, 120) AS sale_datetime,
    CONVERT(varchar(10), start_date, 120) AS start_date,
    CONVERT(varchar(10), end_date, 120) AS end_date,
    duration_days,
    status,
    booking_status_ref,
    booking_status_name,
    doc_posted,
    doc_marked,
    register_duration_days,
    is_active_on_cutoff,
    is_finished_before_cutoff,
    days_to_end,
    days_since_end,
    REPLACE(REPLACE(REPLACE(raw_club, CHAR(9), N' '), CHAR(10), N' '), CHAR(13), N' ') AS raw_club,
    normalized_club,
    REPLACE(REPLACE(REPLACE(club_source, CHAR(9), N' '), CHAR(10), N' '), CHAR(13), N' ') AS club_source,
    REPLACE(REPLACE(REPLACE(sale_branch_raw, CHAR(9), N' '), CHAR(10), N' '), CHAR(13), N' ') AS sale_branch_raw,
    sale_branch,
    REPLACE(REPLACE(REPLACE(sale_branch_source, CHAR(9), N' '), CHAR(10), N' '), CHAR(13), N' ') AS sale_branch_source,
    REPLACE(REPLACE(REPLACE(raw_source, CHAR(9), N' '), CHAR(10), N' '), CHAR(13), N' ') AS raw_source,
    doc_duration_value,
    rg_duration_days,
    rg_freeze_days,
    rg_guests,
    rg_price,
    rg_paid_candidate,
    rg_payment_count_candidate,
    rg_visits_candidate_8007,
    rg_visits_candidate_8008,
    rg_visits_candidate_8009,
    subrent_visit_limit,
    subrent_active_by_dates_on_cutoff,
    subrent_finished_by_dates_before_cutoff,
    subrent_rg3336_receipt_qty,
    subrent_rg3336_expense_qty,
    subrent_rg3336_signed_balance,
    subrent_rg3336_visit_doc_expense_qty,
    subrent_rg3336_receipt_rows,
    subrent_rg3336_expense_rows,
    REPLACE(REPLACE(REPLACE(subrent_rg3336_case_group, CHAR(9), N' '), CHAR(10), N' '), CHAR(13), N' ') AS subrent_rg3336_case_group,
    matched_payment_ref,
    CONVERT(varchar(19), matched_payment_datetime, 120) AS matched_payment_datetime,
    matched_payment_amount,
    REPLACE(REPLACE(REPLACE(matched_payment_method, CHAR(9), N' '), CHAR(10), N' '), CHAR(13), N' ') AS matched_payment_method,
    REPLACE(REPLACE(REPLACE(matched_payment_operation, CHAR(9), N' '), CHAR(10), N' '), CHAR(13), N' ') AS matched_payment_operation,
    matched_payment_match_source,
    membership_sale_line_amount,
    membership_sale_line_count,
    document131_refund_count,
    document131_posted_unmarked_refund_count,
    CONVERT(varchar(19), cutoff_at, 120) AS cutoff_at
FROM fitbase_part2.membership_import_facts
ORDER BY client_id, sale_datetime, subscription_ref;
